COSINE SIMILARITY BETWEEN TWO DOCUMENTS
---------------------------------------

In [2]:
import nltk

In [3]:
#vectoriser and cosine siilarity
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
s1=["In computer science, artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines, in contrast to the natural intelligence displayed by humans and animals. Leading AI textbooks define the field as the study of intelligent agents: "]
s2=["artificial intelligence (AI), sometimes called machine intelligence because machine learning is a subset of artificial intelligence"]

In [5]:
# create the transform
vectorizer = CountVectorizer(stop_words='english')
# tokenize and build vocab
vectorizer.fit(s1)


CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [6]:
# summarize
print(vectorizer.vocabulary_)

{'computer': 5, 'science': 18, 'artificial': 3, 'intelligence': 12, 'ai': 1, 'called': 4, 'machine': 15, 'demonstrated': 8, 'machines': 16, 'contrast': 6, 'natural': 17, 'displayed': 9, 'humans': 11, 'animals': 2, 'leading': 14, 'textbooks': 20, 'define': 7, 'field': 10, 'study': 19, 'intelligent': 13, 'agents': 0}


In [7]:
# encode document
vector = vectorizer.transform(s1)

In [8]:
# summarize encoded vector
print(vector.shape)
print(type(vector))
print(vector.toarray())
vec1=vector.toarray()

(1, 21)
<class 'scipy.sparse.csr.csr_matrix'>
[[1 2 1 1 1 1 1 1 1 1 1 1 4 1 1 1 1 1 1 1 1]]


In [9]:
print(vectorizer.vocabulary_)

{'computer': 5, 'science': 18, 'artificial': 3, 'intelligence': 12, 'ai': 1, 'called': 4, 'machine': 15, 'demonstrated': 8, 'machines': 16, 'contrast': 6, 'natural': 17, 'displayed': 9, 'humans': 11, 'animals': 2, 'leading': 14, 'textbooks': 20, 'define': 7, 'field': 10, 'study': 19, 'intelligent': 13, 'agents': 0}


In [10]:
#vectorise second document
vector = vectorizer.transform(s2)
print(vector.toarray())
vec2=vector.toarray()

[[0 1 0 2 1 0 0 0 0 0 0 0 3 0 0 2 0 0 0 0 0]]


In [11]:
#finding cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(vec1,vec2)

array([[0.69798244]])

In [12]:
cosine_similarity(vec1,vec1)

array([[1.]])

**RESULT**

Here the 2 documents we provided are having 69 as cosine similarity therefor it is closer to 1 than 0 hence this documents can be said to SIMILAR means the vectors are not perpendicular and parallel BUT CLOSER TO PARALLEL)

**rules**

if the cosine similarity is 1 ,then the agngles value is 0 degree and the vectors are said to be parallel

if the cosine value is 0 and value of the angle is 90 degrees ,then the vectors are said to be perpendicular