# LAB 3------12/06/2021

In [ ]:
#1. Mere Wordlist --- STOPWORDS
#2. Word List with Information (Pronunciation in this case) ---CMU WORDLIST
#3. Word List with Semantic Orientation --- WORDNET

In [100]:
#STOPWORDS
from nltk.corpus import stopwords
stopwords.words('english')[:50]

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be']

In [101]:
# stop words for french
from nltk.corpus import stopwords
stopwords.words('french')[:50]

['au',
 'aux',
 'avec',
 'ce',
 'ces',
 'dans',
 'de',
 'des',
 'du',
 'elle',
 'en',
 'et',
 'eux',
 'il',
 'ils',
 'je',
 'la',
 'le',
 'les',
 'leur',
 'lui',
 'ma',
 'mais',
 'me',
 'même',
 'mes',
 'moi',
 'mon',
 'ne',
 'nos',
 'notre',
 'nous',
 'on',
 'ou',
 'par',
 'pas',
 'pour',
 'qu',
 'que',
 'qui',
 'sa',
 'se',
 'ses',
 'son',
 'sur',
 'ta',
 'te',
 'tes',
 'toi',
 'ton']

In [105]:
import os
os.listdir('C:\Users\ACER\Anaconda3\envs\pmdarima\Lib\site-packages\sklearn\feature_extraction\__pycache__\_stop_words.cpython-35.pyc')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-105-af4c9025ea94>, line 2)

In [1]:
#CMU WORDLIST
import nltk
ntries=nltk.corpus.cmudict.entries()
len(ntries)

133737

In [2]:
ntries[:100]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [10]:
#3.wordnet contains word set and having its synonims also
from nltk.corpus import wordnet as wn
wn.synsets('machine')

[Synset('machine.n.01'),
 Synset('machine.n.02'),
 Synset('machine.n.03'),
 Synset('machine.n.04'),
 Synset('machine.n.05'),
 Synset('car.n.01'),
 Synset('machine.v.01'),
 Synset('machine.v.02')]

In [11]:
wn.synset('car.n.01').lemma_names()

['car', 'auto', 'automobile', 'machine', 'motorcar']

In [32]:
wn.synset('machine.v.02').lemma_names()

['machine']

In [37]:
wn.synsets('car')

[Synset('car.n.01'),
 Synset('car.n.02'),
 Synset('car.n.03'),
 Synset('car.n.04'),
 Synset('cable_car.n.01')]

In [33]:
wn.synset('machine.n.01').lemma_names()

['machine']

In [12]:
#task 2-sample text classifier returns last letter of the word
def gender_features(word):
    return{'last_letter':word[-1]}

In [13]:
gender_features('Obama')

{'last_letter': 'a'}

In [14]:
#getting names and labels from the text files
from nltk.corpus import names
labeled_names = ([(name, 'male') for name in names.words('male.txt')]+
[(name, 'female') for name in names.words('female.txt')])

In [15]:
#names in male.txt
from nltk.corpus import names
names.words('male.txt')[:10]

['Aamir',
 'Aaron',
 'Abbey',
 'Abbie',
 'Abbot',
 'Abbott',
 'Abby',
 'Abdel',
 'Abdul',
 'Abdulkarim']

In [16]:
#names in femaile.txt
from nltk.corpus import names
names.words('female.txt')[:10]

['Abagael',
 'Abagail',
 'Abbe',
 'Abbey',
 'Abbi',
 'Abbie',
 'Abby',
 'Abigael',
 'Abigail',
 'Abigale']

In [17]:
girlnames=names.words('female.txt')

In [18]:
#checking deepthi is present in the list or not
res = any(ele in 'deepthi' for ele in girlnames) 
res

False

In [19]:
res = any(ele in 'Abagael' for ele in girlnames) 
res

True

In [20]:
import random
random.shuffle(labeled_names)

In [21]:
#extracting features
featuresets=[(gender_features(n),gender) for (n,gender) in labeled_names]

In [23]:
#our extracted feature set
featuresets[:10]

[({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'g'}, 'male'),
 ({'last_letter': 'o'}, 'male'),
 ({'last_letter': 'e'}, 'female'),
 ({'last_letter': 'n'}, 'male'),
 ({'last_letter': 'e'}, 'male'),
 ({'last_letter': 'e'}, 'female'),
 ({'last_letter': 'e'}, 'female'),
 ({'last_letter': 'l'}, 'male'),
 ({'last_letter': 'l'}, 'female')]

In [16]:
train_set,test_set=featuresets[500:],featuresets[:500]

In [18]:
import nltk
classifier=nltk.NaiveBayesClassifier.train(train_set)

In [20]:
classifier.classify(gender_features('Deepthi'))

'female'

In [21]:
#wrong
classifier.classify(gender_features('Obama'))

'female'

In [22]:
#wrong
classifier.classify(gender_features('Michelle'))


'female'

In [23]:
classifier.classify(gender_features('David'))

'male'

In [24]:
#accuracy of our classifier
print(nltk.classify.accuracy(classifier,test_set))

0.77


In [3]:
#vectoriser and cosine siilarity
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
#getting vectors
vect=CountVectorizer(binary=True)
corpus = ["Tessaract is good optical character recognition engine  ", "optical character recognition is significant "]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [5]:
#creating vocabolary
vocab=vect.vocabulary_

In [6]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [7]:
print(vect.transform(["This is a good optical illusion"]).toarray())

[[0 0 1 1 1 0 0 0]]


In [8]:
print(vect.transform([" optical illusion and recognition is good"]).toarray())

[[0 0 1 1 1 1 0 0]]


In [9]:
print(vect.transform(["This is a good optical illusion"]))

  (0, 2)	1
  (0, 3)	1
  (0, 4)	1


In [10]:
#finding cosine similarity of s1 and s2
#vectorizing s1
s1=vect.transform(["This is a good optical illusion"]).toarray()

In [11]:
#vectorizing s2
s2=vect.transform(corpus).toarray()

In [12]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 1 1 0 1]
 [1 0 0 1 1 1 1 0]]


In [13]:
#finding cosine similarity
similarity = cosine_similarity(s1,s2)

In [14]:
similarity

array([[0.65465367, 0.51639778]])

In [22]:
#cosine similarity example 1
similarity1 = cosine_similarity(vect.transform(["Tessaract is good optical character recognition engine"]).toarray(), vect.transform(["OCR is an optical character recognition engine"]).toarray())

In [23]:
similarity1

array([[0.84515425]])